export const FETCH_STOCKS_REQUEST  = 'FETCH_STOCKS_REQUEST';
export const FETCH_STOCKS_SUCCESS  = 'FETCH_STOCKS_SUCCESS';
export const FETCH_STOCKS_FAILURE  = 'FETCH_STOCKS_FAILURE';
export const BUY_IPHONE            = 'BUY_IPHONE';
export const UPDATE_STOCK_SUCCESS  = 'UPDATE_STOCK_SUCCESS';
